export const LOAD_POSTS_SUCCESS = 'LOAD_POSTS_SUCCESS'
export const LOAD_POST_SUCCESS = 'LOAD_POST_SUCCESS'
export const SAVE_POST_SUCCESS = 'SAVE_POST_SUCCESS'
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'